### ISSUE TITLE
reach seems not to be working correctly

### ISSUE THREAD

**Issue by BrandowLucas** [decryller/wraith#4]
reach seems to work only after several hits even though i set it to 6 blocks.

i tested it on lunar 1.7 and forge 1.7/1.8, same issues.

**Comment by decryller** [comment]
Reach's memory address appears only after hitting something a couple times.
Wraith constantly loops through a selected amount of memory pages searching for specific, well-tested, and reliable patterns in order to find the correct reach address, since changing the wrong address could potentially lead to a Minecraft crash.
For now, all things considered, this is the best we have.

**Comment by BrandowLucas** [comment]
Fair enough.
